/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

typedef volatile unsigned int vuint32_t;

#define RCC_BASE 0x40021000
#define GPIOA_BASE 0x40010800

#define RCC_APB2ENR *((vuint32_t*)(RCC_BASE + 0X18))
#define RCC_IOPAEN (1<<2)

#define GPIOA_CRH *((vuint32_t*)(GPIOA_BASE + 0X04))

#define RCC_CR *((vuint32_t*)(RCC_BASE + 0X00))
typedef union{
	vuint32_t ALL_FIELDS;
	struct
	{
		vuint32_t Reserved:24;
		vuint32_t PLLON:1;

	} Bit ;
}R_RCC_CR_t;
#define RCC_CFGR *((vuint32_t*)(RCC_BASE + 0X04))
typedef union{
	vuint32_t ALL_FIELDS;
	struct
	{
		vuint32_t SW:2;
		vuint32_t SWS:2;
		vuint32_t HPRE:4;
		vuint32_t PPRE1:3;
		vuint32_t PPRE2:3;
		vuint32_t ADCPRE:2;
		vuint32_t PLLSCR:1;
		vuint32_t PLLXTPRE:1;
		vuint32_t PLLMUL:4;

	} Bit ;
}R_RCC_CFGR_t;

typedef union{
	vuint32_t ALL_FIELDS;
	struct
	{
		vuint32_t reserved:13;
		vuint32_t P_13:1;
	} Pin ;
}R_ODR_t;

volatile R_ODR_t* R_ODR = (volatile R_ODR_t*)(GPIOA_BASE + 0X0C);
volatile R_RCC_CFGR_t* R_RCC_CFGR = (volatile R_RCC_CFGR_t*)(RCC_BASE + 0X04);
volatile R_RCC_CR_t* R_RCC_CR = (volatile R_RCC_CR_t*)(RCC_BASE + 0X00);

int main(void)
{
	R_RCC_CFGR->Bit.PLLSCR 	= 0b0	;			// PLL source clock is HSI
	R_RCC_CFGR->Bit.PLLMUL 	= 0b0110;			// PLL multiplexer *8
	R_RCC_CR->Bit.PLLON 	= 0b1	;			// Switching PLL circuit ON
	R_RCC_CFGR->Bit.HPRE 	= 0b0000;			// AHB prescaler /1
	R_RCC_CFGR->Bit.PPRE1 	= 0b100	;			// APB1 prescaler /2
	R_RCC_CFGR->Bit.PPRE2 	= 0b101	;			// APB2 prescaler /4
	R_RCC_CFGR->Bit.SW 		= 0b10	;			// PLL is system clock



	int i;
	RCC_APB2ENR |= RCC_IOPAEN;
	GPIOA_CRH 	&= 0xff0fffff;
	GPIOA_CRH	|= 0x00200000;
	while(1){
		R_ODR->Pin.P_13 = 1;
		for (i = 0; i < 5000; ++i);
		R_ODR->Pin.P_13 = 0;
		for (i = 0; i < 5000; ++i);
	}
	return 0;
}
